apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"commandpod","namespace":"default"},"spec":{"containers":[{"command":["bash","-c","date"],"image":"ubuntu:latest","name":"apna-ubuntu"}],"restartPolicy":"Never"}}
  creationTimestamp: "2024-11-18T10:30:10Z"
  name: commandpod
  namespace: default
  resourceVersion: "5275"
  uid: fbc5ba13-6e90-4e56-8657-081ba77a148a
spec:
  containers:
  - command:
    - bash
    - -c
    - date
    image: ubuntu:latest
    imagePullPolicy: Always
    name: apna-ubuntu
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xv2wc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-xv2wc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-11-18T10:30:16Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-11-18T10:30:10Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-11-18T10:30:10Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-11-18T10:30:10Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-11-18T10:30:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cb195a8ac0523bf107f5e9b359cbfb5753fc16ee3db7b1f7e7438f6215acdc34
    image: ubuntu:latest
    imageID: docker-pullable://ubuntu@sha256:278628f08d4979fb9af9ead44277dbc9c92c2465922310916ad0c46ec9999295
    lastState: {}
    name: apna-ubuntu
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://cb195a8ac0523bf107f5e9b359cbfb5753fc16ee3db7b1f7e7438f6215acdc34
        exitCode: 0
        finishedAt: "2024-11-18T10:30:13Z"
        reason: Completed
        startedAt: "2024-11-18T10:30:13Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xv2wc
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  phase: Succeeded
  qosClass: BestEffort
  startTime: "2024-11-18T10:30:10Z"
