apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: kubeserve
spec:
  containers:
    - name: postres-container
      image: postgres:latest
      env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: pass
      ports:
        - containerPort: 5432
    - name: pgadmin-container
      image: elestio/pgadmin
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: test@gmail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        - name: PGADMIN_LISTEN_PORT
          value: "8080"
        - name: PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT
          value: 'False'
        - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED
          value: 'False'
      ports:
        - containerPort: 8080