apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: hello-nginx-container
        image: nginxdemos/hello