// here the pipeline doesn't continue if testcases fail
pipeline {
    agent any
    tools { 
        maven 'MAVEN' 
        jdk 'jdk17'
    }
    stages{
        stage('Build') {
            steps {
                script {
                    // Change the directory to the subfolder (`demo`) before running the build
                    dir('demo') {
                        // Example for Maven (change if using Gradle or other tools)
                        sh './mvnw clean install -DskipTests'  // Build project inside 'demo' folder
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Run tests inside the 'demo' folder
                    dir('demo') {
                        // Example for Maven (change if using Gradle or other tools)
                        sh './mvnw test'  // Run tests inside 'demo' folder
                    }
                }
            }
        }
    
        
    }
        post {
        always {
            echo 'I have finished'
            deleteDir() // clean up workspace
        }
        success {
            echo 'I succeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things are different...'
        }
    }
    
}
