apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-pod
spec:
  # no restart policy
  containers:
    - name: apna-busybox
      image: busybox:latest
      command: ["sh","-c","touch /tmp/live && sleep 60 && rm /tmp/live && sleep 600"]
      livenessProbe:
        exec:
          command: ["sh","-c","cat /tmp/live"]
        initialDelaySeconds: 5
        periodSeconds: 5