apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - image: sonarqube:latest
      name: sonar
      resources:
        limits:
          cpu: "2"
          memory: "7000M"
        requests:
          cpu: "2"
          memory: "1024M"
      ports:
        - containerPort: 9000

    - image: nginx:alpine
      name: apna-nginx
      resources:
        limits:
          cpu: "0.5"
          memory: "1024M"
        requests:
          cpu: "0.5"
          memory: "64M"
      ports:
        - containerPort: 80